require('opts')
require('keys')
require('plug')
require('terminal')
require('autopairs')
require('line')
require('spell')
require('wk')

-- lsp
require('lsp.cmp')
require('lsp.lsp-config')
require('lsp.lsp-installer')
require('lsp.treesitter_config')
require('lsp.tree')
